name: GitHub 3D Contribution Graph

# Run this workflow every day at midnight
on:
  schedule:
    - cron: "0 0 * * *"
  # Allow manual trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate 3D Contribution Graph
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Generate 3D Contribution Graph
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          
      - name: Commit and Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "Updated 3D Contribution Graph" || echo "No changes to commit"
          git push
