name: GitHub 3D Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"  # This runs at midnight every day
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate 3D Contribution Graph
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Generate 3D Contribution Graph
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      
      - name: Verify Output
        run: |
          if [ -d "profile-3d-contrib" ]; then
            echo "✅ 3D Contribution graph generated successfully!"
            ls -la profile-3d-contrib/
          else
            echo "❌ Failed to generate 3D contribution graph"
            exit 1
          fi
          
      - name: Commit and Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "Updated 3D Contribution Graph" || echo "No changes to commit"
          git push
